Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,10 +1,12 @@
 name: GitHub Actions Demo
-run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
 on: [push, pull_request]
 jobs:
-  Explore-GitHub-Actions:
+  Build-and-Test:
     runs-on: ubuntu-latest
     steps:
+      - name: Check out repository code
+        uses: actions/checkout@v4
+      
       - name: Set up JDK 11
         uses: actions/setup-java@v3
         with:
@@ -12,9 +14,13 @@ jobs:
           distribution: 'temurin'
           cache: maven
       
-      - name: Check out repository code
-        uses: actions/checkout@v4
-
+      - name: Verify `pom.xml` exists
+        run: |
+          if [ ! -f "./pom.xml" ]; then
+            echo "Error: pom.xml not found. Check your repository structure.";
+            exit 1;
+          fi
+      
       - name: Build and Test with Maven
         run: |
           mvn clean install
